---
spring:
  application:
    name: bookkeeping
  profiles:
    active: local
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8070
---
spring:
  profiles: local
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/bookkeeping
    username: bookkeeper
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: false
---
spring:
  profiles: dev
#  more to come
